name: Publish to PyPI

on:
  release:
    types: released

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build distribution
      run: |
        python -m build
    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@release/v1
